### ISSUE TITLE
Wordpress plugin missing values folder

### ISSUE THREAD

**Issue by wstudios** [42Telecom/wordpress-plugin-two-factor-authentication#1]
A website I am working on, used the update feature to update the two factor plugin. Unfortunately it broke the site and the issue is related to missing files/folders. Please check the zip you submitted to wordpress plugins directory. Thanks.

**Comment by sebastien-lemarinel** [comment]
Hello,

Can you give me a little bit more of details ? Version of Wordpress ? What are the files/folder who are missing ? 

Thx.

**Comment by wstudios** [comment]
No prob. I am using the latest 4.5.1 Wordpress and the entire fortytwo-two-factor-authentication/src/Value folder is missing.

**Comment by sebastien-lemarinel** [comment]
Ok. Yes it seem the SVN repository isn't tracking this directory on the wordpress repository. I will check and fix this problem ASAP.

**Comment by sebastien-lemarinel** [comment]
Just added the missing files in the Wordpress repository and tested it.
Everything seem to work normally now. Sorry for the inconvenience.

**Comment by wstudios** [comment]
Thank you, plugin works great btw.

**Comment by sebastien-lemarinel** [comment]
Thx for the feedback.
